'use strict';

// X25519 through Node's OpenSSL, against the JavaScript implementation it
// replaces.
//
// This is the one change in the library where "it looks right" is worth
// nothing. A shared secret that differs in one byte does not throw — it
// produces a session that encrypts fine and decrypts to noise on the other
// side, and the failure surfaces days later as messages that never arrive. So
// every operation is compared byte for byte against curve25519-js over random
// inputs, and the two signature operations are checked to still be the
// JavaScript ones rather than quietly swapped for Ed25519.

const test   = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');

const curveJs = require('curve25519-js');
const curve   = require('../lib/curve');

const b = (x) => Buffer.from(x);

test('Node X25519 is actually being used', () => {
  // If this is false the rest of the file still passes — it would be comparing
  // curve25519-js against itself — so say so loudly rather than pass quietly.
  assert.equal(curve.NATIVE, true,
    'the native path is not active, so these comparisons prove nothing here');
});

// ─── byte-for-byte, over random inputs ───────────────────────────────────────

test('generateKeyPair returns the same pair as curve25519-js', () => {
  for (let i = 0; i < 200; i++) {
    const seed = crypto.randomBytes(32);
    const js   = curveJs.generateKeyPair(seed);
    const ours = curve.generateKeyPair(seed);

    assert.equal(ours.private.toString('hex'), b(js.private).toString('hex'),
      'private half, seed ' + seed.toString('hex'));
    assert.equal(ours.public.toString('hex'), b(js.public).toString('hex'),
      'public half, seed ' + seed.toString('hex'));
  }
});

test('the private half is clamped, not the raw seed', () => {
  // curve25519-js clamps before returning. A caller stores what it is handed,
  // so returning the raw seed instead would write sessions the old code cannot
  // read back.
  const seed = Buffer.alloc(32, 0xff);
  const { private: priv } = curve.generateKeyPair(seed);
  assert.equal(priv[0] & 0b111, 0, 'low three bits cleared');
  assert.equal(priv[31] & 0b1000_0000, 0, 'top bit cleared');
  assert.equal(priv[31] & 0b0100_0000, 0b0100_0000, 'second-top bit set');
  assert.notEqual(priv.toString('hex'), seed.toString('hex'));
});

test('the caller\'s seed is not modified', () => {
  const seed = crypto.randomBytes(32);
  const before = seed.toString('hex');
  curve.generateKeyPair(seed);
  assert.equal(seed.toString('hex'), before, 'clamping must work on a copy');
});

test('sharedKey agrees with curve25519-js', () => {
  for (let i = 0; i < 200; i++) {
    const a = curveJs.generateKeyPair(crypto.randomBytes(32));
    const c = curveJs.generateKeyPair(crypto.randomBytes(32));

    const js   = b(curveJs.sharedKey(a.private, c.public));
    const ours = curve.sharedKey(b(a.private), b(c.public));
    assert.equal(ours.toString('hex'), js.toString('hex'));
  }
});

test('both sides of an exchange reach the same secret', () => {
  // The property that actually matters, stated directly rather than inferred
  // from agreeing with another implementation.
  for (let i = 0; i < 50; i++) {
    const a = curve.generateKeyPair(crypto.randomBytes(32));
    const c = curve.generateKeyPair(crypto.randomBytes(32));
    assert.equal(
      curve.sharedKey(a.private, c.public).toString('hex'),
      curve.sharedKey(c.private, a.public).toString('hex')
    );
  }
});

test('a pair generated by one implementation works with the other', () => {
  // Sessions written before this change are read after it, so the two must
  // interoperate in both directions, not merely produce equal outputs when fed
  // identical inputs.
  const oldPair = curveJs.generateKeyPair(crypto.randomBytes(32));
  const newPair = curve.generateKeyPair(crypto.randomBytes(32));

  assert.equal(
    curve.sharedKey(b(oldPair.private), newPair.public).toString('hex'),
    b(curveJs.sharedKey(newPair.private, b(oldPair.public))).toString('hex')
  );
});

test('a seed of all zeroes, and of all ones, still agree', () => {
  for (const seed of [Buffer.alloc(32, 0x00), Buffer.alloc(32, 0xff)]) {
    const js   = curveJs.generateKeyPair(seed);
    const ours = curve.generateKeyPair(seed);
    assert.equal(ours.public.toString('hex'), b(js.public).toString('hex'),
      'seed ' + seed[0].toString(16));
  }
});

// ─── the signatures must NOT have moved ──────────────────────────────────────

test('sign is still XEdDSA, matching curve25519-js exactly', () => {
  for (let i = 0; i < 50; i++) {
    const kp  = curveJs.generateKeyPair(crypto.randomBytes(32));
    const msg = crypto.randomBytes(1 + Math.floor(Math.random() * 200));

    // XEdDSA is deterministic in this implementation, so the bytes must match.
    assert.equal(
      curve.sign(b(kp.private), msg).toString('hex'),
      b(curveJs.sign(kp.private, msg)).toString('hex')
    );
  }
});

test('a signature written before this change still verifies', () => {
  const kp  = curveJs.generateKeyPair(crypto.randomBytes(32));
  const msg = Buffer.from('device identity', 'utf8');
  const old = b(curveJs.sign(kp.private, msg));

  assert.equal(curve.verify(b(kp.public), msg, old), true);
  assert.equal(curveJs.verify(kp.public, msg, curve.sign(b(kp.private), msg)), true,
    'and one written now verifies with the old code');
});

test('verify rejects a tampered message and a tampered signature', () => {
  const kp  = curveJs.generateKeyPair(crypto.randomBytes(32));
  const msg = Buffer.from('hello', 'utf8');
  const sig = curve.sign(b(kp.private), msg);

  assert.equal(curve.verify(b(kp.public), Buffer.from('hellp', 'utf8'), sig), false);
  const bad = Buffer.from(sig); bad[0] ^= 1;
  assert.equal(curve.verify(b(kp.public), msg, bad), false);
});

// ─── refuses what it cannot do, rather than doing it wrongly ─────────────────

test('a key of the wrong length is refused', () => {
  const ok = crypto.randomBytes(32);
  assert.throws(() => curve.generateKeyPair(crypto.randomBytes(31)), /32 bytes/);
  assert.throws(() => curve.generateKeyPair(null), /32 bytes/);
  assert.throws(() => curve.sharedKey(crypto.randomBytes(31), ok), /private key must be 32/);
  assert.throws(() => curve.sharedKey(ok, crypto.randomBytes(33)), /public key must be 32/);
});

test('a Uint8Array is accepted wherever a Buffer is', () => {
  const seed = new Uint8Array(crypto.randomBytes(32));
  const kp   = curve.generateKeyPair(seed);
  const peer = curve.generateKeyPair(crypto.randomBytes(32));

  assert.equal(
    curve.sharedKey(new Uint8Array(kp.private), new Uint8Array(peer.public)).toString('hex'),
    curve.sharedKey(kp.private, peer.public).toString('hex')
  );
});

// ─── nothing goes back to the JavaScript implementation by accident ──────────

test('no module imports curve25519-js except lib/curve.js', () => {
  const { execSync } = require('node:child_process');
  const hits = execSync(
    "grep -rln \"require('curve25519-js')\" lib/ --include=*.js || true",
    { cwd: __dirname + '/..' }
  ).toString().trim().split('\n').filter(Boolean);

  assert.deepEqual(hits, ['lib/curve.js'],
    'curve25519-js is 19x slower on the hot path; lib/curve.js is the one place ' +
    'that may reach for it, and only for the XEdDSA signatures Node cannot do');
});

test('the JavaScript fallback produces the same bytes as the native path', () => {
  // A Node built without X25519 falls back, and that path had nothing
  // exercising it — the one branch where a bug would only ever appear on
  // someone else's machine. Hide the primitive, reload the module, compare.
  const seed = crypto.randomBytes(32);
  const peer = curveJs.generateKeyPair(crypto.randomBytes(32));
  const nativeKp = curve.generateKeyPair(seed);
  const nativeSh = curve.sharedKey(nativeKp.private, b(peer.public));

  const real = crypto.diffieHellman;
  delete crypto.diffieHellman;
  for (const k of Object.keys(require.cache)) {
    if (/lib[\\/]curve\.js$/.test(k)) delete require.cache[k];
  }
  try {
    const fallback = require('../lib/curve');
    assert.equal(fallback.NATIVE, false, 'the fallback is what is running');

    const kp = fallback.generateKeyPair(seed);
    assert.equal(kp.private.toString('hex'), nativeKp.private.toString('hex'));
    assert.equal(kp.public.toString('hex'), nativeKp.public.toString('hex'));
    assert.equal(
      fallback.sharedKey(kp.private, b(peer.public)).toString('hex'),
      nativeSh.toString('hex')
    );
  } finally {
    crypto.diffieHellman = real;
    for (const k of Object.keys(require.cache)) {
      if (/lib[\\/]curve\.js$/.test(k)) delete require.cache[k];
    }
  }
});
